### ISSUE TITLE
Installing on an M1 mac gives esbuild arm64 not compatible

### ISSUE THREAD

**Issue by nicholas-keers** [datasprayio/open-next-cdk#51]
On trying to install `open-next-cdk` using:

`yarn add -D esbuild@0.17.16 open-next-cdk`

I am getting:

```
yarn add v1.22.19
warning package.json: No license field
warning deploy@0.1.0: No license field
[1/4] 🔍  Resolving packages...
warning open-next-cdk > @aws-sdk/signature-v4@3.374.0: This package has moved to @smithy/signature-v4
[2/4] 🚚  Fetching packages...
error @esbuild/darwin-x64@0.17.16: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.
```

It looks to be because the root `package.json` does not have an `@esbuild/darwin-arm64` entry. Is it possible to add this?

**Comment by matusfaro** [comment]
@nicholas-keers Yes of course. Added now, it will take a bit of time for new version to publish.
